publishDir = "public"
baseURL = 'https://blog.hivein.app/'  # Change later to blog.hivein.app
languageCode = 'en-us'
title = 'HiveIn Blog'
enableRobotsTXT = true

[params]
  author = "Team HiveIn"
  description = "A blog about modern relationships, rituals, and real connection."
